import { User, UserRole } from '../types';

export type Permission =
  // Old permissions for backward compatibility
  | 'VIEW_ADMIN_DASHBOARD'
  | 'MANAGE_USERS'
  | 'MANAGE_BUSINESS_RULES'
  | 'VIEW_CUSTOMER_DASHBOARD'
  | 'SEND_PARCEL'
  | 'TRACK_PARCEL'
  | 'VIEW_MERCHANT_DASHBOARD'
  | 'MANAGE_OWN_SHIPMENTS'
  | 'VIEW_OWN_PROTECTION'
  | 'VIEW_POINT_DASHBOARD'
  | 'MANAGE_OWN_CENTER'
  | 'MANAGE_POINT_STAFF'
  | 'VIEW_OWN_EARNINGS'
  | 'VIEW_OWN_INVENTORY'
  | 'VIEW_LOGISTICS_DASHBOARD'
  | 'MANAGE_OWN_FLEET'
  | 'VIEW_ASSIGNED_ROUTES'
  | 'UPDATE_ASSIGNED_TASKS'
  | 'ACCESS_SUPPORT'
  | 'ACCESS_FINANCE'
  | 'MANAGE_PAYOUTS'
  | 'MANAGE_PROTECTION'
  | 'ACCESS_VERIFICATION'
  | 'ACCESS_VERIFICATION_QUEUE'
  | 'VIEW_OPERATIONAL_REPORTS'
  | 'MONITOR_OPERATIONS'
  // New Granular permissions requested
  | 'USERS_VIEW' | 'USERS_CREATE' | 'USERS_EDIT' | 'USERS_SUSPEND' | 'USERS_DELETE'
  | 'SHIPMENTS_VIEW' | 'SHIPMENTS_EDIT' | 'SHIPMENTS_ASSIGN' | 'SHIPMENTS_CANCEL'
  | 'SAFEPAY_VIEW' | 'SAFEPAY_RELEASE' | 'SAFEPAY_HOLD' | 'SAFEPAY_REFUND' | 'SAFEPAY_CONFIGURE'
  | 'DISPUTES_VIEW' | 'DISPUTES_INVESTIGATE' | 'DISPUTES_ASSIGN' | 'DISPUTES_RESOLVE' | 'DISPUTES_CLOSE'
  | 'CHAT_VIEW_AUTHORIZED' | 'CHAT_ACCESS_EVIDENCE' | 'CHAT_ADD_CASE_NOTES'
  | 'SUPPORT_VIEW_TICKETS' | 'SUPPORT_RESPOND' | 'SUPPORT_ESCALATE' | 'SUPPORT_CLOSE'
  | 'CENTRES_VIEW' | 'CENTRES_APPROVE' | 'CENTRES_SUSPEND' | 'CENTRES_EDIT'
  | 'SETTINGS_VIEW' | 'SETTINGS_EDIT'
  | 'AUDIT_VIEW' | 'AUDIT_EXPORT';

const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  CUSTOMER: ['VIEW_CUSTOMER_DASHBOARD', 'TRACK_PARCEL'],
  MERCHANT: ['VIEW_MERCHANT_DASHBOARD', 'SEND_PARCEL', 'TRACK_PARCEL', 'MANAGE_OWN_SHIPMENTS', 'VIEW_OWN_PROTECTION'],
  CENTER_OWNER: [
    'VIEW_POINT_DASHBOARD', 'MANAGE_OWN_CENTER', 'MANAGE_POINT_STAFF',
    'VIEW_OWN_EARNINGS', 'VIEW_OWN_INVENTORY', 'TRACK_PARCEL'
  ],
  CENTER_STAFF: ['VIEW_POINT_DASHBOARD', 'VIEW_OWN_INVENTORY', 'TRACK_PARCEL', 'UPDATE_ASSIGNED_TASKS'],
  LOGISTICS_COMPANY: ['VIEW_LOGISTICS_DASHBOARD', 'MANAGE_OWN_FLEET', 'VIEW_OWN_EARNINGS', 'TRACK_PARCEL'],
  DRIVER: ['VIEW_LOGISTICS_DASHBOARD', 'VIEW_ASSIGNED_ROUTES', 'UPDATE_ASSIGNED_TASKS', 'TRACK_PARCEL'],
  DEVELOPER: ['TRACK_PARCEL', 'SEND_PARCEL', 'SHIPMENTS_VIEW'],
  API_MERCHANT_PARTNER: ['TRACK_PARCEL', 'SEND_PARCEL', 'SHIPMENTS_VIEW', 'SAFEPAY_VIEW'],

  SUPPORT_OFFICER: [
    'ACCESS_SUPPORT', 'TRACK_PARCEL',
    'DISPUTES_VIEW', 'DISPUTES_INVESTIGATE', 'CHAT_VIEW_AUTHORIZED', 'CHAT_ADD_CASE_NOTES',
    'SUPPORT_VIEW_TICKETS', 'SUPPORT_RESPOND', 'SUPPORT_ESCALATE'
  ],
  VERIFICATION_OFFICER: [
    'ACCESS_VERIFICATION', 'ACCESS_VERIFICATION_QUEUE',
    'USERS_VIEW', 'CENTRES_VIEW'
  ],
  FINANCE_OFFICER: [
    'ACCESS_FINANCE', 'MANAGE_PAYOUTS', 'MANAGE_PROTECTION', 'MANAGE_BUSINESS_RULES',
    'SAFEPAY_VIEW', 'SAFEPAY_RELEASE', 'SAFEPAY_HOLD', 'SAFEPAY_REFUND'
  ],
  OPERATIONS_MANAGER: [
    'VIEW_ADMIN_DASHBOARD', 'VIEW_OPERATIONAL_REPORTS', 'MONITOR_OPERATIONS', 'MANAGE_BUSINESS_RULES',
    'USERS_VIEW', 'USERS_CREATE', 'USERS_EDIT',
    'SHIPMENTS_VIEW', 'SHIPMENTS_EDIT', 'SHIPMENTS_ASSIGN',
    'CENTRES_VIEW', 'CENTRES_APPROVE', 'CENTRES_SUSPEND', 'CENTRES_EDIT',
    'SETTINGS_VIEW', 'AUDIT_VIEW'
  ],

  SUPER_ADMIN: [
    'VIEW_ADMIN_DASHBOARD', 'MANAGE_USERS', 'MANAGE_BUSINESS_RULES',
    'ACCESS_SUPPORT', 'ACCESS_FINANCE', 'ACCESS_VERIFICATION',
    'VIEW_OPERATIONAL_REPORTS', 'MONITOR_OPERATIONS', 'MANAGE_PAYOUTS', 'MANAGE_PROTECTION',

    // All Granular
    'USERS_VIEW', 'USERS_CREATE', 'USERS_EDIT', 'USERS_SUSPEND', 'USERS_DELETE',
    'SHIPMENTS_VIEW', 'SHIPMENTS_EDIT', 'SHIPMENTS_ASSIGN', 'SHIPMENTS_CANCEL',
    'SAFEPAY_VIEW', 'SAFEPAY_RELEASE', 'SAFEPAY_HOLD', 'SAFEPAY_REFUND', 'SAFEPAY_CONFIGURE',
    'DISPUTES_VIEW', 'DISPUTES_INVESTIGATE', 'DISPUTES_ASSIGN', 'DISPUTES_RESOLVE', 'DISPUTES_CLOSE',
    'CHAT_VIEW_AUTHORIZED', 'CHAT_ACCESS_EVIDENCE', 'CHAT_ADD_CASE_NOTES',
    'SUPPORT_VIEW_TICKETS', 'SUPPORT_RESPOND', 'SUPPORT_ESCALATE', 'SUPPORT_CLOSE',
    'CENTRES_VIEW', 'CENTRES_APPROVE', 'CENTRES_SUSPEND', 'CENTRES_EDIT',
    'SETTINGS_VIEW', 'SETTINGS_EDIT',
    'AUDIT_VIEW', 'AUDIT_EXPORT'
  ],
  DISPUTE_ADMIN: [
    'ACCESS_SUPPORT', 'TRACK_PARCEL', 'MANAGE_PROTECTION',
    'DISPUTES_VIEW', 'DISPUTES_INVESTIGATE', 'DISPUTES_ASSIGN', 'DISPUTES_RESOLVE', 'DISPUTES_CLOSE',
    'CHAT_VIEW_AUTHORIZED', 'CHAT_ACCESS_EVIDENCE', 'CHAT_ADD_CASE_NOTES',
    'SAFEPAY_VIEW', 'SAFEPAY_HOLD', 'SAFEPAY_REFUND', 'SAFEPAY_RELEASE'
  ],
  SUPPORT_ADMIN: [
    'ACCESS_SUPPORT', 'TRACK_PARCEL',
    'SUPPORT_VIEW_TICKETS', 'SUPPORT_RESPOND', 'SUPPORT_ESCALATE', 'SUPPORT_CLOSE',
    'CHAT_VIEW_AUTHORIZED', 'CHAT_ADD_CASE_NOTES'
  ],
  OPERATIONS_ADMIN: [
    'VIEW_ADMIN_DASHBOARD', 'VIEW_OPERATIONAL_REPORTS', 'MONITOR_OPERATIONS', 'MANAGE_BUSINESS_RULES',
    'SHIPMENTS_VIEW', 'SHIPMENTS_EDIT', 'SHIPMENTS_ASSIGN', 'SHIPMENTS_CANCEL',
    'CENTRES_VIEW', 'CENTRES_APPROVE', 'CENTRES_SUSPEND', 'CENTRES_EDIT',
    'SETTINGS_VIEW', 'SETTINGS_EDIT'
  ],
  VERIFICATION_ADMIN: [
    'ACCESS_VERIFICATION', 'ACCESS_VERIFICATION_QUEUE',
    'USERS_VIEW', 'USERS_EDIT', 'USERS_SUSPEND',
    'CENTRES_VIEW', 'CENTRES_APPROVE', 'CENTRES_SUSPEND'
  ],
  SECURITY_ADMIN: [
    'VIEW_ADMIN_DASHBOARD', 'MANAGE_USERS',
    'USERS_VIEW', 'USERS_EDIT', 'USERS_SUSPEND', 'USERS_DELETE',
    'AUDIT_VIEW', 'AUDIT_EXPORT'
  ],
  FINANCE_ADMIN: [
    'ACCESS_FINANCE', 'MANAGE_PAYOUTS', 'MANAGE_PROTECTION', 'MANAGE_BUSINESS_RULES',
    'SAFEPAY_VIEW', 'SAFEPAY_RELEASE', 'SAFEPAY_HOLD', 'SAFEPAY_REFUND', 'SAFEPAY_CONFIGURE',
    'SETTINGS_VIEW', 'SETTINGS_EDIT',
    'AUDIT_VIEW', 'AUDIT_EXPORT'
  ],
  DISPATCH_RIDER: [
    'VIEW_ASSIGNED_ROUTES', 'UPDATE_ASSIGNED_TASKS', 'TRACK_PARCEL', 'VIEW_OWN_EARNINGS'
  ],
  DISPATCH_COMPANY: [
    'VIEW_LOGISTICS_DASHBOARD', 'MANAGE_OWN_FLEET', 'VIEW_OWN_EARNINGS', 'TRACK_PARCEL'
  ],
  FLEET_MANAGER: [
    'VIEW_LOGISTICS_DASHBOARD', 'MANAGE_OWN_FLEET', 'UPDATE_ASSIGNED_TASKS', 'TRACK_PARCEL'
  ]
};

class PermissionService {
  private static instance: PermissionService;

  private constructor() {}

  public static getInstance(): PermissionService {
    if (!PermissionService.instance) {
      PermissionService.instance = new PermissionService();
    }
    return PermissionService.instance;
  }

  hasPermission(user: User | null, permission: Permission): boolean {
    if (!user) return false;

    // 1. Check if user has a role that has SUPER_ADMIN
    if (user.roles.includes('SUPER_ADMIN')) return true;

    // 2. Check custom permissions assigned directly to this user profile
    if (user.customPermissions && Array.isArray(user.customPermissions) && user.customPermissions.includes(permission)) {
      return true;
    }

    // 3. Check all user's roles
    return user.roles.some(role => ROLE_PERMISSIONS[role as UserRole]?.includes(permission));
  }

  getPermissionsForRole(role: UserRole): Permission[] {
    return ROLE_PERMISSIONS[role] || [];
  }
}

export const permissionService = PermissionService.getInstance();
