import { ParcelStatus } from '../types';

const VALID_TRANSITIONS: Record<ParcelStatus, ParcelStatus[]> = {
  'DRAFT': ['AWAITING_PAYMENT', 'CANCELLED'],
  'AWAITING_PAYMENT': ['PAYMENT_CONFIRMED', 'CANCELLED'],
  'PAYMENT_CONFIRMED': ['AWAITING_DROP_OFF', 'CANCELLED'],
  'AWAITING_DROP_OFF': ['RECEIVED_AT_ORIGIN', 'CANCELLED', 'EXPIRED'],
  'RECEIVED_AT_ORIGIN': ['AWAITING_DISPATCH', 'READY_FOR_PICKUP', 'CANCELLED', 'DAMAGED'],
  'AWAITING_DISPATCH': ['IN_TRANSIT', 'CANCELLED', 'LOST'],
  'IN_TRANSIT': ['TRANSFERRED_BETWEEN_POINTS', 'ARRIVED_AT_DESTINATION', 'LOST', 'DAMAGED'],
  'TRANSFERRED_BETWEEN_POINTS': ['IN_TRANSIT', 'ARRIVED_AT_DESTINATION', 'LOST', 'DAMAGED'],
  'ARRIVED_AT_DESTINATION': ['READY_FOR_PICKUP', 'LOST', 'DAMAGED'],
  'READY_FOR_PICKUP': ['COLLECTED', 'EXPIRED', 'RETURNED'],
  'COLLECTED': ['DELIVERED', 'COMPLETED', 'DISPUTED'],
  'DELIVERED': ['COMPLETED', 'DISPUTED', 'REFUND_PENDING'],
  'COMPLETED': ['ARCHIVED'],
  'CANCELLED': ['ARCHIVED'],
  'EXPIRED': ['RETURNED', 'ARCHIVED'],
  'LOST': ['REFUND_PENDING', 'ARCHIVED'],
  'DAMAGED': ['REFUND_PENDING', 'RETURNED', 'ARCHIVED'],
  'RETURNED': ['COMPLETED', 'ARCHIVED'],
  'REFUND_PENDING': ['COMPLETED', 'ARCHIVED'],
  'DISPUTED': ['REFUND_PENDING', 'COMPLETED', 'ARCHIVED'],
  'RECEIVED_AT_CENTER': ['READY_FOR_PICKUP', 'DAMAGED', 'LOST'],
  'PENDING_WE_SABI_DELIVERY': ['RECEIVED_AT_CENTER', 'CANCELLED', 'LOST', 'EXCEPTION'],
  'EXCEPTION': ['AWAITING_DISPATCH', 'IN_TRANSIT', 'READY_FOR_PICKUP', 'RETURNED', 'DAMAGED', 'LOST', 'ARCHIVED'],
  'ARCHIVED': []
};

export function isValidStatusTransition(current: ParcelStatus, next: ParcelStatus): boolean {
  return VALID_TRANSITIONS[current].includes(next);
}
